export const messageTypes = {
  ADD_MESSAGE: 'ADD_MESSAGE',
  DELETE_MESSAGE: 'DELETE_MESSAGE',
  SELECT_MESSAGE: 'SELECT_MESSAGE',
  DESELECT_MESSAGE: 'DESELECT_MESSAGE',
  CLEAR_BOARD: 'CLEAR_BOARD',
};

export default messageTypes;
