export const messageTypes = {
  GET_MESSAGES: 'GET_MESSAGES',
  ADD_MESSAGE: 'ADD_MESSAGE',
  UPDATE_MESSAGE_SCORE: 'UPDATE_MESSAGE_SCORE',
  DELETE_MESSAGE: 'DELETE_MESSAGE',
  DELETE_ALL_MESSAGES: 'DELETE_ALL_MESSAGES',
  SELECT_MESSAGE: 'SELECT_MESSAGE',
  DESELECT_MESSAGE: 'DESELECT_MESSAGE',
};

export default messageTypes;
